export default function projects() {
    return [
        {
            "name" : "Plant shop",
            "background": "bg-15",
            "description": "Portfolio-project-12",
            "id": 12,
            "demo": "https://plant-shop-79b92.firebaseapp.com/",
            "repo": "https://github.com/galdranorn/plant-shop",
        },
        {
            "name" : "Furniture shop - group project",
            "background": "bg-9",
            "description": "Portfolio-project-11",
            "id": 11,
            "demo": "https://romantic-volhard-ce5aef.netlify.com/",
            "repo": "https://github.com/galdranorn/furnitures-shop-WDP181103",
        },
        {
            "name" : "Sudoku game",
            "background": "bg-13",
            "description": "Portfolio-project-10",
            "id": 10,
            "row": "projects2",
            "repo": "https://github.com/galdranorn/sudoku-reactJS",
        },
        {
            "name" : "GitHub User Searcher",
            "background": "bg-8",
            "description": "Portfolio-project-9",
            "id": 9,
            "demo": "https://galdranorn.github.io/github-user-searcher",
            "repo": "https://github.com/galdranorn/github-user-searcher",
        },
        {
            "name" : "Gif Searcher",
            "background": "bg-10",
            "description": "Portfolio-project-8",
            "id": 8,
            "demo": "https://galdranorn.github.io/gif-searcher",
            "repo": "https://github.com/galdranorn/gif-searcher",
        },
        {
            "name" : "Draxton Quiz",
            "background": "bg-4",
            "description": "Portfolio-project-7",
            "id": 7,
            "demo": "https://galdranorn.github.io/quiz/",
            "repo": "https://github.com/galdranorn/quiz",
        },
        {
            "name" : "Awax project",
            "background": "bg-7",
            "description": "Portfolio-project-6",
            "id": 6,
            "demo": "https://galdranorn.github.io/awax-project/",
            "repo": "https://github.com/galdranorn/awax-project",
        },
        {
            "name" : "Country searcher",
            "background": "bg-6",
            "description": "Portfolio-project-5",
            "id": 5,
            "demo": "https://galdranorn.github.io/country-searcher/",
            "repo": "https://github.com/galdranorn/country-searcher",
        },
        {
            "name" : "Round the World",
            "background": "bg-3",
            "description": "Portfolio-project-4",
            "id": 4,
            "demo": "https://galdranorn.github.io/round-the-world-trip/",
            "repo": "https://github.com/galdranorn/round-the-world-trip",
        },
        {
            "name" : "Rock paper scissors game",
            "background": "bg-5",
            "description": "Portfolio-project-3",
            "id": 3,
            "demo": "https://galdranorn.github.io/rock-paper-scissors/",
            "repo": "https://github.com/galdranorn/rock-paper-scissors",
        },
        {
            "name" : "Administration Panel",
            "background": "bg-2",
            "description": "Portfolio-project-2",
            "id": 2,
            "demo": "https://galdranorn.github.io/administration-panel/",
            "repo": "https://github.com/galdranorn/administration-panel",
        },
        {
            "name" : "Golden Project",
            "background": "bg-1",
            "description": "Portfolio-project-1",
            "id": 1,
            "demo": "https://galdranorn.github.io/golden-project/",
            "repo": "https://github.com/galdranorn/golden-project",
        },
    ]
}